{% set name = "ibm-platform-services" %}
{% set version = "0.64.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: cd5e47e1d4381d90cec0928d805504b251f6f10b605fbd97a018cb1247be1542

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=67.7.2
  run:
    - python >={{ python_min }}
    - ibm-cloud-sdk-core >=3.22.1,<4.0.0

test:
  imports:
    - ibm_platform_services
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/IBM/platform-services-python-sdk
  summary: Python client library for IBM Cloud Platform Services
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wshanks
