{% set name = "ibm-platform-services" %}
{% set version = "0.55.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ibm-platform-services-{{ version }}.tar.gz
  sha256: 2554683df328bd490002dbd1fb5ff5c30a134183562041bfa352300ed3ca64a9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - ibm-cloud-sdk-core <4.0.0,>=3.20.3

test:
  imports:
    - ibm_platform_services
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/IBM/platform-services-python-sdk
  summary: Python client library for IBM Cloud Platform Services
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wshanks
