{% set name = "ibm-platform-services" %}
{% set version = "0.37.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ibm-platform-services-{{ version }}.tar.gz
  sha256: 291a48370cde2d498e6fc2a5bdfbad9f2e2241a92b800bc18f9e96c4b2fc42f7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - requests <3.0.0,>=2.31.0
    - urllib3 <2.0.0,>=1.26.0
    - python-dateutil <3.0.0,>=2.5.3
    - ibm-cloud-sdk-core <4.0.0,>=3.16.7

test:
  imports:
    - ibm_platform_services
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/IBM/platform-services-python-sdk
  summary: Python client library for IBM Cloud Platform Services
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wshanks
