{% set name = "ibm-platform-services" %}
{% set version = "0.56.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 00f9351b3cda68d8bd603aec71f214fae8d47c377d45ba35c99f528cf44985a5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - ibm-cloud-sdk-core >=3.20.6,<4.0.0

test:
  imports:
    - ibm_platform_services
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/IBM/platform-services-python-sdk
  summary: Python client library for IBM Cloud Platform Services
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wshanks
