{% set name = "ibm-platform-services" %}
{% set version = "0.58.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 1b1c322208f3781155b58032cb66bed63ae55f6b3d191d4e63143ebd311d5c56

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools >=67.7.2
  run:
    - python >=3.8
    - ibm-cloud-sdk-core >=3.22.0,<4.0.0

test:
  imports:
    - ibm_platform_services
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/IBM/platform-services-python-sdk
  summary: Python client library for IBM Cloud Platform Services
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wshanks
