schema_version: 1

context:
  name: ibm-platform-services
  version: "0.77.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: dedadfef98b9b8f8a40e1edba0ef3a7137ef46894e61699f775dad7c2f12fbd1

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=67.7.2
  run:
    - python >=${{ python_min }}
    - ibm-cloud-sdk-core >=3.24.4,<4.0.0

tests:
  - python:
      imports:
        - ibm_platform_services
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Python client library for IBM Cloud Platform Services
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/IBM/platform-services-python-sdk

extra:
  recipe-maintainers:
    - wshanks
